"""Fix typo summary_feedback

Revision ID: 2b1007c03f92
Revises: a20f8749e06c
Create Date: 2025-09-29 02:20:30.283328

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2b1007c03f92'
down_revision: Union[str, Sequence[str], None] = 'a20f8749e06c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('summary_feedback', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.drop_column('sessions', 'summary_feedack')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('summary_feedack', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.drop_column('sessions', 'summary_feedback')
    # ### end Alembic commands ###
