"""Create Session and Turn table

Revision ID: 58441eb33646
Revises: bbed3b7ce268
Create Date: 2025-08-05 00:48:57.035002

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58441eb33646'
down_revision: Union[str, Sequence[str], None] = 'bbed3b7ce268'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_usage'), table_name='otp')
    op.create_index('ix_user_usage_created', 'otp', ['user_id', 'usage', 'created_at'], unique=False)
    op.create_index('idx_password_reset_cleanup', 'password_reset_token', ['exp', 'used'], unique=False)
    op.create_index('idx_password_reset_user_created', 'password_reset_token', ['user_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_password_reset_user_created', table_name='password_reset_token')
    op.drop_index('idx_password_reset_cleanup', table_name='password_reset_token')
    op.drop_index('ix_user_usage_created', table_name='otp')
    op.create_index(op.f('ix_user_usage'), 'otp', ['user_id', 'usage'], unique=False)
    # ### end Alembic commands ###
