"""Remove turn no from Turn

Revision ID: 65754363c494
Revises: d048c6e174a9
Create Date: 2025-08-22 10:42:57.500003

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65754363c494'
down_revision: Union[str, Sequence[str], None] = 'd048c6e174a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_turns_turn_no'), table_name='turns')
    op.drop_column('turns', 'turn_no')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('turns', sa.Column('turn_no', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_turns_turn_no'), 'turns', ['turn_no'], unique=False)
    # ### end Alembic commands ###
