"""Add Password Reset Token

Revision ID: 70966b46b118
Revises: 6ceb0992e00f
Create Date: 2025-08-02 12:52:33.938087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70966b46b118'
down_revision: Union[str, Sequence[str], None] = '6ceb0992e00f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('password_reset_token',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('exp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_password_reset_token_created_at'), 'password_reset_token', ['created_at'], unique=False)
    op.create_index(op.f('ix_password_reset_token_exp'), 'password_reset_token', ['exp'], unique=False)
    op.create_index(op.f('ix_password_reset_token_used'), 'password_reset_token', ['used'], unique=False)
    op.create_index(op.f('ix_password_reset_token_user_id'), 'password_reset_token', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_password_reset_token_user_id'), table_name='password_reset_token')
    op.drop_index(op.f('ix_password_reset_token_used'), table_name='password_reset_token')
    op.drop_index(op.f('ix_password_reset_token_exp'), table_name='password_reset_token')
    op.drop_index(op.f('ix_password_reset_token_created_at'), table_name='password_reset_token')
    op.drop_table('password_reset_token')
    # ### end Alembic commands ###
