"""Made password opt removed verified flag and added mode flag with server default

Revision ID: 80492bb69a4d
Revises: d2f17542d303
Create Date: 2025-09-15 22:40:30.336576

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80492bb69a4d'
down_revision: Union[str, Sequence[str], None] = 'd2f17542d303'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('mode', sa.String(), server_default='email', nullable=False))
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index(op.f('ix_users_verified'), table_name='users')
    op.drop_index(op.f('ix_verified_created'), table_name='users')
    op.drop_column('users', 'verified')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('verified', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_verified_created'), 'users', ['verified', 'created_at'], unique=False)
    op.create_index(op.f('ix_users_verified'), 'users', ['verified'], unique=False)
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('users', 'mode')
    # ### end Alembic commands ###
