"""Add composite index

Revision ID: bbed3b7ce268
Revises: 70966b46b118
Create Date: 2025-08-02 19:22:11.018044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bbed3b7ce268'
down_revision: Union[str, Sequence[str], None] = '70966b46b118'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('otp_otp_key'), 'otp', type_='unique')
    op.create_index('ix_used_exp', 'otp', ['used', 'exp'], unique=False)
    op.create_index('ix_user_usage', 'otp', ['user_id', 'usage'], unique=False)
    op.create_index('ix_exp_used', 'refresh_tokens', ['exp', 'used'], unique=False)
    op.create_index('ix_verified_created', 'users', ['verified', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_verified_created', table_name='users')
    op.drop_index('ix_exp_used', table_name='refresh_tokens')
    op.drop_index('ix_user_usage', table_name='otp')
    op.drop_index('ix_used_exp', table_name='otp')
    op.create_unique_constraint(op.f('otp_otp_key'), 'otp', ['otp'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
