"""Add Usage Field in OTP

Revision ID: c5510ad086be
Revises: 360eaa17fdc0
Create Date: 2025-07-31 16:37:02.012854

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5510ad086be'
down_revision: Union[str, Sequence[str], None] = '360eaa17fdc0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('otp', sa.Column('usage', sa.String(), nullable=False))
    op.create_index(op.f('ix_otp_created_at'), 'otp', ['created_at'], unique=False)
    op.create_index(op.f('ix_otp_exp'), 'otp', ['exp'], unique=False)
    op.create_index(op.f('ix_otp_used'), 'otp', ['used'], unique=False)
    op.create_index(op.f('ix_otp_user_id'), 'otp', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_otp_user_id'), table_name='otp')
    op.drop_index(op.f('ix_otp_used'), table_name='otp')
    op.drop_index(op.f('ix_otp_exp'), table_name='otp')
    op.drop_index(op.f('ix_otp_created_at'), table_name='otp')
    op.drop_column('otp', 'usage')
    # ### end Alembic commands ###
