"""Remvoe ai and user speech link

Revision ID: d2f17542d303
Revises: 4976dea84834
Create Date: 2025-09-12 01:21:06.916883

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2f17542d303'
down_revision: Union[str, Sequence[str], None] = '4976dea84834'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('turns', 'ai_speech_link')
    op.drop_column('turns', 'user_speech_link')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('turns', sa.Column('user_speech_link', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('turns', sa.Column('ai_speech_link', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
